#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MIMSPhotoUploader.Resource", IsApplication=true)]

namespace MIMSPhotoUploader
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::MIMSPhotoUploader.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::MIMSPhotoUploader.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int borrowpit = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int BorrowPitId = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int BorrowPitListItem = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int BorrowPitName = 2131034122;
			
			// aapt resource value: 0x7f05001a
			public const int Borrowpit = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int Image = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int List = 2131034139;
			
			// aapt resource value: 0x7f050016
			public const int Text = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int Text1 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int Text2 = 2131034136;
			
			// aapt resource value: 0x7f05001c
			public const int btnAddPhoto = 2131034140;
			
			// aapt resource value: 0x7f050014
			public const int btnPhoto = 2131034132;
			
			// aapt resource value: 0x7f05002b
			public const int btnQuickAdd = 2131034155;
			
			// aapt resource value: 0x7f050008
			public const int btnSave = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int btnTakePhoto = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int checkUploaded = 2131034130;
			
			// aapt resource value: 0x7f05002a
			public const int editCurentDate = 2131034154;
			
			// aapt resource value: 0x7f050022
			public const int imagePhoto = 2131034146;
			
			// aapt resource value: 0x7f050006
			public const int imageView1 = 2131034118;
			
			// aapt resource value: 0x7f050026
			public const int labelGPSPos = 2131034150;
			
			// aapt resource value: 0x7f050010
			public const int linearLayout1 = 2131034128;
			
			// aapt resource value: 0x7f05001e
			public const int linearLayout3 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int linearLayout4 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int linearLayout5 = 2131034144;
			
			// aapt resource value: 0x7f05001d
			public const int linearLayoutMain = 2131034141;
			
			// aapt resource value: 0x7f05000f
			public const int listBorrowPit = 2131034127;
			
			// aapt resource value: 0x7f050015
			public const int listPhotos = 2131034133;
			
			// aapt resource value: 0x7f050023
			public const int myButton = 2131034147;
			
			// aapt resource value: 0x7f050028
			public const int myPhotos = 2131034152;
			
			// aapt resource value: 0x7f050004
			public const int spinCategory = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int spinner1 = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int textBorrowPitID = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int textBorrowPitName = 2131034114;
			
			// aapt resource value: 0x7f050021
			public const int textBorrowpit = 2131034145;
			
			// aapt resource value: 0x7f050013
			public const int textBorrowpitName = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int textCategory = 2131034115;
			
			// aapt resource value: 0x7f050011
			public const int textCategoryName = 2131034129;
			
			// aapt resource value: 0x7f05002c
			public const int textFilename = 2131034156;
			
			// aapt resource value: 0x7f050027
			public const int textGPSLat = 2131034151;
			
			// aapt resource value: 0x7f050025
			public const int textGPSLong = 2131034149;
			
			// aapt resource value: 0x7f050024
			public const int textGPSNote = 2131034148;
			
			// aapt resource value: 0x7f050000
			public const int textMainTitle = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int textPhotoUri = 2131034119;
			
			// aapt resource value: 0x7f050029
			public const int textSyncStatus = 2131034153;
			
			// aapt resource value: 0x7f05000d
			public const int textView1 = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int textView2 = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddPhotoLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BorrowPitListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FindBorrowpit = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ImageListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ImageListLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int layoutCustomView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int layoutImageList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int layoutListItemTemplate = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int layoutSinglePhoto = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int PhotoDetailActivity = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int PhotoListItem = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int app_name = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int button_Save = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int button_TakePhoto = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int find_borrowpit = 2130968582;
			
			// aapt resource value: 0x7f040013
			public const int gpsOff = 2130968595;
			
			// aapt resource value: 0x7f040003
			public const int hello = 2130968579;
			
			// aapt resource value: 0x7f040012
			public const int labelGPSPos = 2130968594;
			
			// aapt resource value: 0x7f040008
			public const int label_BorrowPitName = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int label_Id = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int label_ManagePhotos = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int label_Roadno = 2130968583;
			
			// aapt resource value: 0x7f040015
			public const int label_borrowPitID = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int label_borrowPitName = 2130968598;
			
			// aapt resource value: 0x7f04000e
			public const int label_photoCategory = 2130968590;
			
			// aapt resource value: 0x7f040004
			public const int photos = 2130968580;
			
			// aapt resource value: 0x7f04000d
			public const int quickphotos = 2130968589;
			
			// aapt resource value: 0x7f040014
			public const int syncNotAvailable = 2130968596;
			
			// aapt resource value: 0x7f04000f
			public const int syncStatus_NothingToSync = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int syncStatus_PhotosToSync = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int textGPSNote = 2130968593;
			
			// aapt resource value: 0x7f040002
			public const int textMainTitle = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
